-- 상품을 구매한 회원 비율 구하기

SELECT YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
    ROUND((COUNT(DISTINCT U.USER_ID) / 
         (SELECT COUNT(USER_ID) 
          FROM USER_INFO
          WHERE YEAR(JOINED) = 2021)), 1) AS PUCHASED_RATIO
FROM USER_INFO U INNER JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)