-- 조건에 부합하는 중고거래 댓글 조회하기

SELECT TITLE, B.BOARD_ID, REPLY_ID, G.WRITER_ID, G.CONTENTS, DATE_FORMAT(G.CREATED_DATE, "%Y-%m-%d") AS 'CREATED_DATE'
FROM USED_GOODS_BOARD B join USED_GOODS_REPLY G ON B.BOARD_ID = G.BOARD_ID
WHERE B.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
ORDER BY G.CREATED_DATE, TITLE;