-- JOIN: 상품을 구매한 회원 비율 구하기(Lv.5)
SELECT YEAR, MONTH, COUNT(*) AS PUCHASED_USERS,
	ROUND((COUNT(*) / (SELECT COUNT(*)
			FROM USER_INFO WHERE YEAR(JOINED) = 2021)
          ), 1) AS PUCHASED_RATIO
FROM (SELECT DISTINCT YEAR(SALE.SALES_DATE) AS YEAR,
        MONTH(SALE.SALES_DATE) AS MONTH, USER.USER_ID
    FROM ONLINE_SALE as SALE
    JOIN USER_INFO as USER
    ON SALE.USER_ID = USER.USER_ID
    WHERE YEAR(JOINED) = 2021) as JOIN_INFO
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;