-- String, Date: 자동차 대여 기록에서 장기/단기 대여 구분하기(Lv.1)
SELECT HISTORY_ID, CAR_ID,
    DATE_FORMAT(START_DATE, "%Y-%m-%d") as START_DATE,
    DATE_FORMAT(END_DATE, "%Y-%m-%d") as END_DATE,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) >= 29
        THEN '장기 대여' 
        ELSE '단기 대여' 
        END as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-09-01' AND '2022-09-30'
ORDER BY HISTORY_ID DESC;