-- JOIN: 상품 별 오프라인 매출 구하기 (Lv.2)
SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) as SALES
FROM PRODUCT
  JOIN OFFLINE_SALE
  ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;