-- JOIN: 조건에 맞는 도서와 저자 리스트 출력하기 (Lv.2)
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK
  JOIN AUTHOR
  ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY LIKE '경제'
ORDER BY PUBLISHED_DATE;