-- 취소되지 않은 진료 예약 조회하기

SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM  APPOINTMENT A 
    LEFT JOIN  PATIENT B 
    ON  A.PT_NO = B.PT_NO 
    LEFT JOIN  DOCTOR C
    ON  A.MDDR_ID = C.DR_ID
WHERE A.MCDP_CD = 'CS'
    AND A.APNT_CNCL_YN = 'N'
    AND LEFT(APNT_YMD,10) = '2022-04-13'
 ORDER BY A.APNT_YMD;