-- 자동차 대여 기록 별 대여 금액 구하기

SELECT HISTORY_ID, ROUND(DAILY_FEE *
    (CASE WHEN (DATEDIFF(END_DATE, START_DATE) + 1) < 7 THEN 1
        WHEN (DATEDIFF(END_DATE, START_DATE) + 1) < 30 THEN 0.95
        WHEN (DATEDIFF(END_DATE, START_DATE) + 1) < 90 THEN 0.92
        ELSE 0.85
    END) * (DATEDIFF(END_DATE, START_DATE) + 1), 0) 'FEE'
FROM CAR_RENTAL_COMPANY_CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
USING (CAR_ID)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC