-- GROUP BY: 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기(Lv.3)
SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(HISTORY_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
        AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
    ) AND START_DATE >= '2022-08-01'
    AND START_DATE <= '2022-10-31'
GROUP BY CAR_ID, MONTH
HAVING RECORDS >= 0
ORDER BY MONTH asc, CAR_ID desc;