-- 입양 시각 구하기(2)

SET @HOUR := -1;
SELECT (@HOUR := @HOUR + 1) AS 'HOUR',
    (SELECT COUNT(ANIMAL_ID)
        FROM ANIMAL_OUTS
        WHERE HOUR(DATETIME) = @HOUR) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE @HOUR < 23