-- JOIN: 없어진 기록 찾기(Lv.3)
SELECT ANIMAL_OUTS.ANIMAL_ID as ANIMAL_ID, ANIMAL_OUTS.NAME as NAME
FROM ANIMAL_INS
  RIGHT JOIN ANIMAL_OUTS
  ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID;