-- JOIN: 있었는데요 없었습니다(Lv.3)
SELECT ANIMAL_INS.ANIMAL_ID as ANIMAL_ID, ANIMAL_INS.NAME as NAME
FROM ANIMAL_INS
  JOIN ANIMAL_OUTS
  ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME;