-- 프로그래머스 - String, Date: 대여 기록이 존재하는 자동차 리스트 구하기(Lv.3)
SELECT CAR.CAR_ID as CAR_ID
FROM CAR_RENTAL_COMPANY_CAR as CAR
WHERE CAR.CAR_ID IN (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as HISTORY
    WHERE START_DATE LIKE '%-10-%')
    AND CAR_TYPE LIKE '세단'
ORDER BY CAR_ID DESC;