-- JOIN: 보호소에서 중성화한 동물(Lv.4)
SELECT outs.ANIMAL_ID as ANIMAL_ID, outs.ANIMAL_TYPE as ANIMAL_TYPE, outs.NAME as NAME
FROM ANIMAL_OUTS as outs
    LEFT JOIN ANIMAL_INS as ins
    ON outs.ANIMAL_ID = ins.ANIMAL_ID
WHERE (SEX_UPON_OUTCOME LIKE 'Spayed%'
       OR SEX_UPON_OUTCOME LIKE 'Neutered%')
    AND SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY ANIMAL_ID;