-- String, Date: 조건에 부합하는 중고거래 상태 조회하기(Lv.2)
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
    CASE WHEN STATUS LIKE 'SALE' THEN '판매중'
        WHEN STATUS LIKE 'RESERVED' THEN '예약중'
        WHEN STATUS LIKE 'DONE' THEN '거래완료' 
        END as STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE LIKE '2022-10-05'
ORDER BY BOARD_ID DESC;