-- 자동차 대여 기록 별 대여 금액 구하기(Lv.4)
SELECT HISTORY_ID,
    ROUND(DAILY_FEE * PERIOD * 
          (100 - IFNULL(PLAN.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (SELECT HISTORY_ID, CAR_TYPE, DATEDIFF(END_DATE, START_DATE) + 1 as PERIOD, DAILY_FEE,
        CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE 'NONE' END AS DUR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR as CAR
        RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as HISTORY
        ON CAR.CAR_ID = HISTORY.CAR_ID
    WHERE CAR.CAR_TYPE LIKE '트럭') as HIS
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as PLAN
    ON HIS.CAR_TYPE = PLAN.CAR_TYPE
        AND HIS.DUR_TYPE = PLAN.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;
