-- 취소되지 않은 진료 예약 조회하기(Lv.4)
SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT, DOCTOR, PATIENT
WHERE APNT_CNCL_YN LIKE 'N'
    AND APPOINTMENT.PT_NO = PATIENT.PT_NO
    AND APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
    AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD;