-- 주문량이 많은 아이스크림들 조회하기

SELECT F.FLAVOR
FROM FIRST_HALF F JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS 'TOTAL_ORDER'
    FROM JULY 
    GROUP BY FLAVOR
) J
ON F.FLAVOR = J.FLAVOR
ORDER BY (J.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3;
