-- 식품분류별 가장 비싼 식품의 정보 조회하기

SELECT CATEGORY, PRICE AS 'MAX_PRICE', PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('국', '과자', '김치', '식용유') AND 
    PRICE IN (SELECT MAX(PRICE)
            FROM FOOD_PRODUCT
            GROUP BY CATEGORY)
ORDER BY PRICE DESC;