-- GROUP BY: 조건에 맞는 사용자와 총 거래금액 조회하기(Lv.3)
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD
    INNER JOIN USED_GOODS_USER
    ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;