-- GROUP BY: 년, 월, 성별 별 상품 구매 회원 수 구하기(Lv.4)
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER,
    COUNT(DISTINCT USER_INFO.USER_ID) as USERS
FROM USER_INFO
    JOIN ONLINE_SALE
    ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;

-- 구매한 회원수를 집계하는 것
-- 같은 회원이 여러번 구매해도 한 번으로 계산해야 함
-- 때문에 COUNT 할 때 DISTINCT 해주기 = 중복 제거