-- 서울에 위치한 식당 목록 출력하기

SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW JOIN REST_INFO 
ON REST_REVIEW.REST_ID = REST_INFO.REST_ID 
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;