-- JOIN: 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기(Lv.4) => 실패
SELECT MONTH_CARS.CAR_ID as CAR_ID, CAR_TYPE, FEE
FROM (SELECT CAR_ID, CAR_RENTAL_COMPANY_CAR.CAR_TYPE as CAR_TYPE,
       FLOOR((DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100)) as FEE
    FROM CAR_RENTAL_COMPANY_CAR
        INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        ON CAR_RENTAL_COMPANY_CAR.CAR_TYPE = CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE
    GROUP BY CAR_ID
    HAVING FEE BETWEEN 500000 AND 2000000
        AND (CAR_TYPE LIKE '세단' OR CAR_TYPE LIKE 'SUV')) as MONTH_CARS
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ON MONTH_CARS.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
WHERE END_DATE < '2022-11-01' || START_DATE > '2022-11-01'
GROUP BY CAR_ID
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;


/*
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 세단, SUV
SELECT CAR_ID, CAR_RENTAL_COMPANY_CAR.CAR_TYPE as CAR_TYPE,
       FLOOR((DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100)) as FEE
    FROM CAR_RENTAL_COMPANY_CAR
        INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        ON CAR_RENTAL_COMPANY_CAR.CAR_TYPE = CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE
    GROUP BY CAR_ID
    HAVING FEE BETWEEN 500000 AND 2000000
        AND (CAR_TYPE LIKE '세단' OR CAR_TYPE LIKE 'SUV');
*/