-- GROUP BY: 성분으로 구분한 아이스크림 총 주문량(Lv.2)
SELECT ICECREAM_INFO.INGREDIENT_TYPE, SUM(FIRST_HALF.TOTAL_ORDER) as 'TOTAL_ORDER'
FROM FIRST_HALF
    JOIN ICECREAM_INFO
    ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
GROUP BY ICECREAM_INFO.INGREDIENT_TYPE
ORDER BY SUM(FIRST_HALF.TOTAL_ORDER);