-- 프로그래머스 SQL 고득점 Kit
-- SELECT: 과일로 만든 아이스크림 고르기(Lv.1)

SELECT FIRST_HALF.FLAVOR as FLAVOR
FROM FIRST_HALF, ICECREAM_INFO
WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
    AND TOTAL_ORDER >= 3000
    AND INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY TOTAL_ORDER DESC;