-- 3월에 태어난 여성 회원 목록 출력하기(Lv.2)
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3
    AND GENDER LIKE "W"
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;