-- 재구매가 일어난 상품과 회원 리스트 구하기(Lv.2)
-- USER_ID, PRODUCT_ID 그룹의 갯수가 2 이상이면 재구매인 것!
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC;