-- 서울에 위치한 식당 목록 출력하기(Lv.4)
SELECT REST_INFO.REST_ID as 'REST_ID', REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) as 'SCORE'
FROM REST_INFO
JOIN REST_REVIEW
    ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
GROUP BY REST_REVIEW.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY AVG(REVIEW_SCORE) DESC, FAVORITES DESC;